name: Deploy to ECS

on:
  push:
    branches:
      - main

permissions:
  id-token: write   
  contents: read  

jobs:
  deploy_to_ecs:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Commit Details
        id: commit_info
        run: |
          echo "COMMIT_ID=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
          echo "APPROVER=$(git log -1 --pretty=format:'%an')" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Secret Scanner
        uses: secret-scanner/action@0.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          aws-region: ap-south-1
          audience: sts.amazonaws.com
          role-session-name: samplerolesession

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Notify Slack on ECR Push Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "Build and push Docker image to ECR in dev is successful\n
            Project: nomad\n
            Environment: staging\n
            Build Number: ${{ env.BUILD_NUMBER }}\n
            Commit ID: ${{ env.COMMIT_ID }}\n
            Commit Message: ${{ env.COMMIT_MESSAGE }}\n
            Approver: ${{ env.APPROVER }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Update new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./task-definition.json  
          container-name: ${{ secrets.CONTAINER_NAME }}
          image: ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Deploy to Amazon ECS 
        id: ecs-deploy
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ secrets.ECS_SERVICE }}
          cluster: ${{ secrets.ECS_CLUSTER }}
          wait-for-service-stability: true

      - name: Notify Slack on ECS Deploy Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text": "Deploy to ECS in dev is successful\n
            Project: nomad\n
            Environment: staging\n
            Build Number: ${{ env.BUILD_NUMBER }}\n
            Commit ID: ${{ env.COMMIT_ID }}\n
            Commit Message: ${{ env.COMMIT_MESSAGE }}\n
            Approver: ${{ env.APPROVER }}"
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
